[package]
name = "audio_visualizer"
version = "0.1.0"
authors = ["Niwo1493 <nicolai-wolfrom@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
dft = "0.5.5"
rodio = "0.11.0"

